[2023-12-04T20:26:01.396+0000] {processor.py:157} INFO - Started process (PID=662) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:26:01.397+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:26:01.398+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:26:01.398+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:26:01.404+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:26:01.403+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:26:01.405+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:26:01.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.027 seconds
[2023-12-04T20:26:31.941+0000] {processor.py:157} INFO - Started process (PID=671) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:26:31.943+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:26:31.945+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:26:31.944+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:26:31.954+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:26:31.952+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:26:31.955+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:26:31.975+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.043 seconds
[2023-12-04T20:27:02.335+0000] {processor.py:157} INFO - Started process (PID=680) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:27:02.338+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:27:02.339+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:27:02.338+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:27:02.346+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:27:02.345+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:27:02.347+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:27:02.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.039 seconds
[2023-12-04T20:27:32.800+0000] {processor.py:157} INFO - Started process (PID=689) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:27:32.802+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:27:32.802+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:27:32.802+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:27:32.808+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:27:32.806+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:27:32.808+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:27:32.825+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.028 seconds
[2023-12-04T20:28:03.344+0000] {processor.py:157} INFO - Started process (PID=698) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:28:03.347+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:28:03.348+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:28:03.348+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:28:03.357+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:28:03.355+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:28:03.358+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:28:03.380+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.043 seconds
[2023-12-04T20:28:33.692+0000] {processor.py:157} INFO - Started process (PID=707) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:28:33.693+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:28:33.694+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:28:33.694+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:28:33.701+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:28:33.700+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:28:33.702+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:28:33.718+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.030 seconds
[2023-12-04T20:29:04.104+0000] {processor.py:157} INFO - Started process (PID=716) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:29:04.105+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:29:04.106+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:29:04.105+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:29:04.111+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:29:04.110+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:29:04.112+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:29:04.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.025 seconds
[2023-12-04T20:29:34.532+0000] {processor.py:157} INFO - Started process (PID=725) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:29:34.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:29:34.535+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:29:34.534+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:29:34.541+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:29:34.539+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:29:34.542+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:29:34.561+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.033 seconds
[2023-12-04T20:30:04.914+0000] {processor.py:157} INFO - Started process (PID=734) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:30:04.915+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:30:04.915+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:30:04.915+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:30:04.922+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:30:04.920+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:30:04.922+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:30:04.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.030 seconds
[2023-12-04T20:30:35.319+0000] {processor.py:157} INFO - Started process (PID=743) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:30:35.321+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:30:35.322+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:30:35.321+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:30:35.326+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:30:35.325+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:30:35.326+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:30:35.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.025 seconds
[2023-12-04T20:31:05.851+0000] {processor.py:157} INFO - Started process (PID=754) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:31:05.852+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:31:05.853+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:31:05.853+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:31:05.860+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:31:05.858+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:31:05.861+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:31:05.882+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.036 seconds
[2023-12-04T20:31:36.270+0000] {processor.py:157} INFO - Started process (PID=764) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:31:36.271+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:31:36.272+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:31:36.272+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:31:36.278+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:31:36.276+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:31:36.279+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:31:36.294+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.029 seconds
[2023-12-04T20:32:06.736+0000] {processor.py:157} INFO - Started process (PID=773) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:32:06.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:32:06.740+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:32:06.740+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:32:06.747+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:32:06.745+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:32:06.748+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:32:06.765+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.037 seconds
[2023-12-04T20:32:37.310+0000] {processor.py:157} INFO - Started process (PID=782) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:32:37.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:32:37.314+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:32:37.313+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:32:37.321+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:32:37.319+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:32:37.321+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:32:37.339+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.036 seconds
[2023-12-04T20:33:07.796+0000] {processor.py:157} INFO - Started process (PID=791) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:33:07.799+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:33:07.800+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:33:07.800+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:33:07.807+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:33:07.805+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:33:07.808+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:33:07.828+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.039 seconds
[2023-12-04T20:33:38.293+0000] {processor.py:157} INFO - Started process (PID=800) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:33:38.295+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:33:38.295+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:33:38.295+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:33:38.302+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:33:38.299+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:33:38.303+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:33:38.325+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.037 seconds
[2023-12-04T20:34:08.757+0000] {processor.py:157} INFO - Started process (PID=809) to work on /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:34:08.760+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/second.py for tasks to queue
[2023-12-04T20:34:08.762+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:34:08.761+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:34:08.769+0000] {logging_mixin.py:154} INFO - [2023-12-04T20:34:08.767+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/second.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/second.py", line 17, in <module>
    start_date=datetime(),
TypeError: function missing required argument 'year' (pos 1)
[2023-12-04T20:34:08.769+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/second.py
[2023-12-04T20:34:08.793+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/second.py took 0.043 seconds
